{
 "title": "Cassandra Testbed",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Twitter App Service QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{response_code=\"200\",reporter=\"destination\"}[3m])) by (destination_app)",
     "legendFormat": "{{destination_app}}"
    }
   ]
  },
  {
   "title": "Twitter App Service Reponse Time (ms)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(istio_request_duration_milliseconds_sum{response_code=\"200\",reporter=\"destination\"}[3m])/rate(istio_request_duration_milliseconds_count{response_code=\"200\",reporter=\"destination\"}[3m]) >= 0) by (destination_app)",
     "legendFormat": "{{destination_app}}"
    }
   ]
  },
  {
   "title": "Twitter App Horizontal Pod Autoscale",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(sum (rate (container_cpu_usage_seconds_total{image!=\"\", pod_name=~\"twitter-cass-api-.*\"}[1m])) by (pod_name))",
     "legendFormat": "twitter-cass-api"
    },
    {
     "expr": "count(sum (rate (container_cpu_usage_seconds_total{image!=\"\", pod_name=~\"twitter-cass-friend-.*\"}[1m])) by (pod_name))",
     "legendFormat": "twitter-cass-friend"
    },
    {
     "expr": "count(sum (rate (container_cpu_usage_seconds_total{image!=\"\", pod_name=~\"twitter-cass-tweet-.*\"}[1m])) by (pod_name))",
     "legendFormat": "twitter-cass-tweet"
    },
    {
     "expr": "count(sum (rate (container_cpu_usage_seconds_total{image!=\"\", pod_name=~\"twitter-cass-user-.*\"}[1m])) by (pod_name))",
     "legendFormat": "twitter-cass-user"
    }
   ]
  },
  {
   "title": "CPU utilization of twitter pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg (rate (container_cpu_usage_seconds_total{image!=\"\", pod_name=~\"twitter-cass-tweet-.*\", container_name=\"twitter-cass-tweet\"}[1m])) + avg (rate (container_cpu_usage_seconds_total{image!=\"\", pod_name=~\"twitter-cass-tweet-.*\", container_name=\"istio-proxy\"}[1m]))",
     "legendFormat": "twitter-cass-tweet"
    },
    {
     "expr": "avg (rate (container_cpu_usage_seconds_total{image!=\"\", pod_name=~\"twitter-cass-api-.*\", container_name=\"twitter-cass-api\"}[1m])) + avg (rate (container_cpu_usage_seconds_total{image!=\"\", pod_name=~\"twitter-cass-api-.*\", container_name=\"istio-proxy\"}[1m]))",
     "legendFormat": "twitter-cass-api"
    }
   ]
  },
  {
   "title": "Node CPU utlization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{id=\"/\"}[3m])",
     "legendFormat": "{{ stackpoint_io_instance_id}}"
    }
   ]
  },
  {
   "title": "All container CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container_name) (rate(container_cpu_usage_seconds_total{image!=\"\", container_name!=\"POD\"}[3m]))",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Cassandra QPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_stats{name=~\"org:apache:cassandra:metrics:table:(write|read)latency:oneminuterate\"}",
     "legendFormat": "{{instance}}-{{name}}"
    }
   ]
  },
  {
   "title": "Cassandra Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "0.001*(cassandra_stats{name=~\"org:apache:cassandra:metrics:table:(write|read)latency:(50thpercentile|99thpercentile|max)\"})",
     "legendFormat": "{{instance}}-{{name}}"
    }
   ]
  },
  {
   "title": "Cassandra Read Latency, 50p (ms)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "0.001*(cassandra_stats{name=~\"org:apache:cassandra:metrics:table:readlatency:50thpercentile\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cassandra Write Latency, 50p (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "0.001*(cassandra_stats{name=~\"org:apache:cassandra:metrics:table:writelatency:50thpercentile\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cassandra Read Latency, max (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "0.001*(cassandra_stats{name=~\"org:apache:cassandra:metrics:table:readlatency:max\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cassandra Write Latency, max (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "0.001*(cassandra_stats{name=~\"org:apache:cassandra:metrics:table:writelatency:max\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}